import React from 'react';
import { View, Text, StyleSheet, ScrollView, Pressable, StatusBar } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Ionicons } from '@expo/vector-icons';
import { useRouter } from 'expo-router';

import { Colors } from '@/src/theme';

export default function TermsScreen() {
  const router = useRouter();

  return (
    <SafeAreaView style={styles.safe} edges={['top', 'bottom']}>
      <StatusBar barStyle="dark-content" backgroundColor={Colors.background} />
      <View style={styles.header}>
        <Pressable onPress={() => router.back()} style={styles.backBtn} testID="back-terms-btn">
          <Ionicons name="arrow-back" size={20} color={Colors.onSurface} />
        </Pressable>
        <Text style={styles.headerTitle}>Terms & Conditions</Text>
        <View style={styles.spacer} />
      </View>

      <ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}>
        <View style={styles.hero}>
          <Ionicons name="document-text" size={36} color="rgba(255,255,255,0.9)" style={{ marginBottom: 14 }} />
          <Text style={styles.heroTitle}>Terms of Use</Text>
          <Text style={styles.heroText}>
            By using BookMyEvents, you agree to these terms. Please read them carefully before using the app. Effective from June 2026.
          </Text>
        </View>

        <TermsSection
          title="1. Acceptance of Terms"
          body={[
            'By signing in and using BookMyEvents, you agree to be bound by these Terms & Conditions',
            'If you do not agree with any part of these terms, you must not use the application',
            'We reserve the right to update these terms at any time. Continued use of the app constitutes acceptance of updated terms',
          ]}
        />

        <TermsSection
          title="2. App Usage Rules"
          body={[
            'BookMyEvents is a venue booking management application intended for venue/hall owners and their authorised managers',
            'You must use the app only for lawful purposes and in accordance with these terms',
            'You must not use the app to store false, misleading, or fraudulent booking information',
            'You must not attempt to access another user\'s data or bypass any security measures in the app',
            'Automated access, scraping, or use of bots is strictly prohibited',
            'The access reference code shared with you is personal and must not be distributed publicly',
          ]}
        />

        <TermsSection
          title="3. Account Responsibilities"
          body={[
            'You are responsible for maintaining the security of your Google account or phone number used to sign in',
            'You are responsible for all activity that occurs under your account',
            'Notify us immediately if you suspect unauthorised access to your account',
            'Each venue owner must maintain their own account and not share login credentials with others (use the Manager Access feature instead)',
          ]}
        />

        <TermsSection
          title="4. Owner Responsibilities"
          body={[
            'The venue owner is fully responsible for the accuracy of all booking records entered into the app',
            'Financial data, payment records, and invoices generated by the app are for internal record-keeping purposes only',
            'The owner is responsible for ensuring their managers use the app appropriately',
            'The owner can grant and revoke manager access at any time from the Settings screen',
            'The owner is responsible for obtaining any necessary consents from clients whose data is entered into the app',
          ]}
        />

        <TermsSection
          title="5. Manager Responsibilities"
          body={[
            'Managers are granted access by the venue owner and must use the app solely for legitimate booking management purposes',
            'Managers can view all bookings, financial data, and create new bookings on behalf of the owner',
            'Managers cannot modify business settings, generate P&L reports, or delete the account',
            'Managers must not misuse or disclose any booking or financial information they access through the app',
            'Manager access can be revoked by the owner at any time without notice',
          ]}
        />

        <TermsSection
          title="6. Intellectual Property"
          body={[
            'BookMyEvents and all its content, features, and functionality are owned by the app creators',
            'You are granted a limited, non-exclusive, non-transferable licence to use the app for its intended purposes',
            'You must not copy, modify, distribute, or create derivative works based on the app',
          ]}
        />

        <TermsSection
          title="7. Disclaimers & Limitation of Liability"
          body={[
            'BookMyEvents is provided "as is" without warranties of any kind, express or implied',
            'We do not guarantee uninterrupted or error-free service',
            'We are not liable for any loss of data, revenue, or business resulting from use of the app',
            'PDF invoices and reports are for reference only and do not constitute official financial or legal documents',
            'You should maintain independent backups of critical business records',
          ]}
        />

        <TermsSection
          title="8. Data Rights & Deletion"
          body={[
            'You have the right to access, correct, and delete all data associated with your account',
            'You can delete your account and all data permanently from Settings → Delete Account',
            'You can also request deletion at the /delete-account web page by entering your email',
            'Upon account deletion, all booking data, financial records, and personal information are permanently removed',
            'We do not retain deleted data in backups after 30 days of deletion',
          ]}
        />

        <TermsSection
          title="9. Governing Law"
          body={[
            'These terms are governed by the laws of India',
            'Any disputes arising from use of the app shall be subject to the jurisdiction of courts in India',
          ]}
        />

        <View style={styles.note}>
          <Ionicons name="mail-outline" size={16} color={Colors.primary} style={{ marginBottom: 8 }} />
          <Text style={styles.noteTitle}>Contact</Text>
          <Text style={styles.noteBody}>
            For any questions about these terms or to request data deletion, please use the Delete Account page in the app or submit a request at /delete-account.
          </Text>
        </View>

        <Text style={styles.footer}>BookMyEvents • Terms & Conditions • June 2026</Text>
      </ScrollView>
    </SafeAreaView>
  );
}

function TermsSection({ title, body }: { title: string; body: string[] }) {
  return (
    <View style={styles.card}>
      <Text style={styles.cardTitle}>{title}</Text>
      {body.map((line, i) => (
        <View key={i} style={styles.bulletRow}>
          <View style={styles.bullet} />
          <Text style={styles.cardBody}>{line}</Text>
        </View>
      ))}
    </View>
  );
}

const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: Colors.background },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  backBtn: {
    width: 40, height: 40, borderRadius: 12,
    backgroundColor: '#fff',
    alignItems: 'center', justifyContent: 'center',
    borderWidth: 1, borderColor: Colors.outlineVariant,
  },
  headerTitle: {
    flex: 1, textAlign: 'center',
    fontSize: 18, fontWeight: '800', color: Colors.onSurface,
    marginHorizontal: 12,
  },
  spacer: { width: 40, height: 40 },
  content: { padding: 16, paddingBottom: 32 },
  hero: { borderRadius: 22, padding: 24, marginBottom: 16, backgroundColor: Colors.primary, alignItems: 'flex-start' },
  heroTitle: { color: '#fff', fontSize: 22, fontWeight: '800', lineHeight: 28 },
  heroText: { color: 'rgba(255,255,255,0.88)', fontSize: 13, lineHeight: 19, marginTop: 8 },
  card: { backgroundColor: '#fff', borderRadius: 18, padding: 18, marginBottom: 12, borderWidth: 1, borderColor: Colors.outlineVariant },
  cardTitle: { fontSize: 14, fontWeight: '800', color: Colors.primary, marginBottom: 12 },
  bulletRow: { flexDirection: 'row', alignItems: 'flex-start', marginBottom: 8 },
  bullet: { width: 5, height: 5, borderRadius: 3, backgroundColor: Colors.primary, marginTop: 7, marginRight: 10, flexShrink: 0 },
  cardBody: { flex: 1, fontSize: 13, lineHeight: 20, color: Colors.onSurfaceVariant },
  note: { marginTop: 4, backgroundColor: Colors.secondaryContainer, borderRadius: 18, padding: 18 },
  noteTitle: { fontSize: 14, fontWeight: '800', color: Colors.onSurface, marginBottom: 6 },
  noteBody: { fontSize: 13, lineHeight: 20, color: Colors.onSurfaceVariant },
  footer: { textAlign: 'center', fontSize: 11, color: Colors.muted, marginTop: 20, paddingBottom: 8 },
});
